export const ROUTES = {
  LOGIN:        '/login',
  DASHBOARD:    '/dashboard',
  MISSIONS:     '/missions',
  FACTURATION:  '/facturation',
  ENCAISSEMENTS:'/encaissements',
  SALAIRES:     '/salaires',
  CHARGES:      '/charges',
  DEPENSES:     '/depenses',
  PETITE_CAISSE:'/petite-caisse',
  TRESORERIE:   '/tresorerie',
  BFR:          '/bfr',
  TVA:          '/tva',
  PARAMETRES:   '/parametres',
  FNE:          '/fne',
} as const;
